"""initial schema

Revision ID: 800d1156146f
Revises: 
Create Date: 2024-10-16 21:05:01.371237

"""
import fastapi_users_db_sqlalchemy
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f6e85ee7053'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term',
    sa.Column('id', sa.BigInteger(),  nullable=False),
    sa.Column('content', sa.String(length=256), nullable=False),
    sa.Column('language', sa.String(length=7), nullable=False),
    sa.Column('additional_content', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content', 'language', name='uq_content_language')
    )
    op.create_index('idx_content_language', 'term', ['content', 'language'], unique=True)
    op.create_table('term_example',
    sa.Column('id', sa.BigInteger(),  nullable=False),
    sa.Column('language', sa.String(length=7), nullable=False),
    sa.Column('content', sa.String(length=256), nullable=False),
    sa.Column('level', sa.String(length=2), nullable=True),
    sa.Column('additional_content', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('native_language', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('cardset',
    sa.Column('id', sa.BigInteger(),  nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_review', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('term_example_translation',
    sa.Column('language', sa.String(length=7), nullable=False),
    sa.Column('translation', sa.String(length=256), nullable=False),
    sa.Column('term_example_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['term_example_id'], ['term_example.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('language', 'term_example_id'),
    sa.UniqueConstraint('language', 'term_example_id', name='uq_language_term_example')
    )
    op.create_table('term_image',
    sa.Column('id', sa.BigInteger(),  nullable=False),
    sa.Column('term_id', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id')
    )
    op.create_table('term_lexical',
    sa.Column('id', sa.BigInteger(),  nullable=False),
    sa.Column('term_id', sa.BigInteger(), nullable=False),
    sa.Column('term_content_id', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('additional_content', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['term_content_id'], ['term.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card',
    sa.Column('id', sa.BigInteger(),  nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_review', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('cardset_id', sa.BigInteger(), nullable=False),
    sa.Column('term_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['cardset_id'], ['cardset.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('term_definition',
    sa.Column('id', sa.BigInteger(),  nullable=False),
    sa.Column('part_of_speech', sa.SmallInteger(), nullable=False),
    sa.Column('content', sa.String(length=512), nullable=False),
    sa.Column('level', sa.String(length=2), nullable=True),
    sa.Column('term_id', sa.BigInteger(), nullable=False),
    sa.Column('term_lexical_id', sa.BigInteger(), nullable=True),
    sa.Column('additional_content', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_lexical_id'], ['term_lexical.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('term_pronunciation',
    sa.Column('id', sa.BigInteger(),  nullable=False),
    sa.Column('phonetic', sa.String(length=256), nullable=False),
    sa.Column('audio_url', sa.String(length=256), nullable=True),
    sa.Column('term_id', sa.BigInteger(), nullable=True),
    sa.Column('term_example_id', sa.BigInteger(), nullable=True),
    sa.Column('term_lexical_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['term_example_id'], ['term_example.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_lexical_id'], ['term_lexical.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_example_id'),
    sa.UniqueConstraint('term_id'),
    sa.UniqueConstraint('term_lexical_id')
    )
    op.create_table('exercise',
    sa.Column('id', sa.BigInteger(),  nullable=False),
    sa.Column('language', sa.String(length=7), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('level', sa.String(length=2), nullable=True),
    sa.Column('term_id', sa.BigInteger(), nullable=True),
    sa.Column('term_example_id', sa.BigInteger(), nullable=True),
    sa.Column('term_pronunciation_id', sa.BigInteger(), nullable=True),
    sa.Column('term_lexical_id', sa.BigInteger(), nullable=True),
    sa.Column('term_definition_id', sa.BigInteger(), nullable=True),
    sa.Column('term_image_id', sa.BigInteger(), nullable=True),
    sa.Column('additional_content', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['term_definition_id'], ['term_definition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_example_id'], ['term_example.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_image_id'], ['term_image.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_lexical_id'], ['term_lexical.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_pronunciation_id'], ['term_pronunciation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('term_definition_translation',
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('translation', sa.String(length=512), nullable=False),
    sa.Column('meaning', sa.String(length=256), nullable=False),
    sa.Column('term_definition_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['term_definition_id'], ['term_definition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('language', 'term_definition_id'),
    sa.UniqueConstraint('language', 'term_definition_id', name='uq_language_term_definition')
    )
    op.create_table('term_example_link',
    sa.Column('id', sa.BigInteger(),  nullable=False),
    sa.Column('highlight', sa.ARRAY(sa.Integer(), dimensions=2), nullable=False),
    sa.Column('term_example_id', sa.BigInteger(), nullable=False),
    sa.Column('term_id', sa.BigInteger(), nullable=True),
    sa.Column('term_definition_id', sa.BigInteger(), nullable=True),
    sa.Column('term_lexical_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['term_definition_id'], ['term_definition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_example_id'], ['term_example.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_lexical_id'], ['term_lexical.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_definition_id', 'term_example_id', name='uq_term_definition_term_example'),
    sa.UniqueConstraint('term_id', 'term_example_id', name='uq_term_term_example'),
    sa.UniqueConstraint('term_lexical_id', 'term_example_id', name='uq_term_lexical_term_example')
    )
    op.create_table('exercise_history',
    sa.Column('id', sa.BigInteger(),  nullable=False),
    sa.Column('exercise_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('request', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_history')
    op.drop_table('term_example_link')
    op.drop_table('term_definition_translation')
    op.drop_table('exercise')
    op.drop_table('term_pronunciation')
    op.drop_table('term_definition')
    op.drop_table('card')
    op.drop_table('term_lexical')
    op.drop_table('term_image')
    op.drop_table('term_example_translation')
    op.drop_table('cardset')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('term_example')
    op.drop_index('idx_content_language', table_name='term')
    op.drop_table('term')
    # ### end Alembic commands ###
