"""inital schema

Revision ID: 8e139a618c68
Revises: 5dae50486734
Create Date: 2024-10-19 21:55:19.368334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e139a618c68'
down_revision: Union[str, None] = '5dae50486734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardset',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_review', sa.DateTime(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('term',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('additional_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_language', 'term', ['content', 'language'], unique=True)
    op.create_table('term_example',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('additional_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_review', sa.DateTime(), nullable=False),
    sa.Column('cardset_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cardset_id'], ['cardset.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('term_example_translation',
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('translation', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('term_example_id', sa.Integer(), nullable=False),
    sa.Column('additional_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['term_example_id'], ['term_example.id'], ),
    sa.PrimaryKeyConstraint('language', 'term_example_id')
    )
    op.create_table('term_image',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id')
    )
    op.create_table('term_lexical',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('term_content_id', sa.Integer(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('additional_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['term_content_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('term_definition',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('part_of_speech', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('term_lexical_id', sa.Integer(), nullable=True),
    sa.Column('additional_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['term_lexical_id'], ['term_lexical.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('term_pronunciation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('phonetic', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('term_example_id', sa.Integer(), nullable=True),
    sa.Column('term_lexical_id', sa.Integer(), nullable=True),
    sa.Column('additional_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['term_example_id'], ['term_example.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['term_lexical_id'], ['term_lexical.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_example_id'),
    sa.UniqueConstraint('term_id'),
    sa.UniqueConstraint('term_lexical_id')
    )
    op.create_table('exercise',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('term_example_id', sa.Integer(), nullable=True),
    sa.Column('term_pronunciation_id', sa.Integer(), nullable=True),
    sa.Column('term_lexical_id', sa.Integer(), nullable=True),
    sa.Column('term_definition_id', sa.Integer(), nullable=True),
    sa.Column('term_image_id', sa.Integer(), nullable=True),
    sa.Column('additional_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['term_definition_id'], ['term_definition.id'], ),
    sa.ForeignKeyConstraint(['term_example_id'], ['term_example.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['term_image_id'], ['term_image.id'], ),
    sa.ForeignKeyConstraint(['term_lexical_id'], ['term_lexical.id'], ),
    sa.ForeignKeyConstraint(['term_pronunciation_id'], ['term_pronunciation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('unique_listen_sentence', 'exercise', ['type', 'language', 'term_example_id', 'term_pronunciation_id'], unique=True, postgresql_where='type = 3')
    op.create_index('unique_listen_term', 'exercise', ['type', 'language', 'term_id', 'term_pronunciation_id'], unique=True, postgresql_where='type = 1')
    op.create_index('unique_listen_term_lexical', 'exercise', ['type', 'language', 'term_lexical_id', 'term_pronunciation_id'], unique=True, postgresql_where='type = 1')
    op.create_index('unique_listen_term_mchoice', 'exercise', ['type', 'language', 'term_id', 'term_pronunciation_id'], unique=True, postgresql_where='type = 2')
    op.create_index('unique_order_sentence', 'exercise', ['type', 'language', 'term_example_id'], unique=True, postgresql_where='type = 0')
    op.create_index('unique_speak_sentence', 'exercise', ['type', 'language', 'term_example_id'], unique=True, postgresql_where='type = 5')
    op.create_index('unique_speak_term', 'exercise', ['type', 'language', 'term_id'], unique=True, postgresql_where='type = 4')
    op.create_index('unique_speak_term_lexical', 'exercise', ['type', 'language', 'term_lexical_id'], unique=True, postgresql_where='type = 4')
    op.create_index('unique_term_conection', 'exercise', ['type', 'language', 'term_id'], unique=True, postgresql_where='type = 10')
    op.create_index('unique_term_definition_mchoice', 'exercise', ['type', 'language', 'term_definition_id', 'term_id'], unique=True, postgresql_where='type = 7')
    op.create_index('unique_term_image_mchoice', 'exercise', ['type', 'language', 'term_id', 'term_image_id', 'term_pronunciation_id'], unique=True, postgresql_where='type = 8')
    op.create_index('unique_term_image_mchoice_text', 'exercise', ['type', 'language', 'term_id', 'term_image_id'], unique=True, postgresql_where='type = 9')
    op.create_index('unique_term_lexical_mchoice', 'exercise', ['type', 'language', 'term_example_id', 'term_lexical_id'], unique=True, postgresql_where='type = 6')
    op.create_index('unique_term_mchoice', 'exercise', ['type', 'language', 'term_id', 'term_example_id'], unique=True, postgresql_where='type = 6')
    op.create_table('term_definition_translation',
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('translation', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('meaning', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('term_definition_id', sa.Integer(), nullable=False),
    sa.Column('additional_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['term_definition_id'], ['term_definition.id'], ),
    sa.PrimaryKeyConstraint('language', 'term_definition_id')
    )
    op.create_table('term_example_link',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('highlight', sa.ARRAY(sa.Integer(), dimensions=2), nullable=True),
    sa.Column('term_example_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('term_definition_id', sa.Integer(), nullable=True),
    sa.Column('term_lexical_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['term_definition_id'], ['term_definition.id'], ),
    sa.ForeignKeyConstraint(['term_example_id'], ['term_example.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['term_lexical_id'], ['term_lexical.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_definition_id', 'term_example_id', name='term_example_link_term_definition_term_example'),
    sa.UniqueConstraint('term_id', 'term_example_id', name='term_example_link_term_term_example'),
    sa.UniqueConstraint('term_lexical_id', 'term_example_id', name='term_example_link_term_lexical_term_example')
    )
    op.create_table('exercise_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_history')
    op.drop_table('term_example_link')
    op.drop_table('term_definition_translation')
    op.drop_index('unique_term_mchoice', table_name='exercise', postgresql_where='type = 6')
    op.drop_index('unique_term_lexical_mchoice', table_name='exercise', postgresql_where='type = 6')
    op.drop_index('unique_term_image_mchoice_text', table_name='exercise', postgresql_where='type = 9')
    op.drop_index('unique_term_image_mchoice', table_name='exercise', postgresql_where='type = 8')
    op.drop_index('unique_term_definition_mchoice', table_name='exercise', postgresql_where='type = 7')
    op.drop_index('unique_term_conection', table_name='exercise', postgresql_where='type = 10')
    op.drop_index('unique_speak_term_lexical', table_name='exercise', postgresql_where='type = 4')
    op.drop_index('unique_speak_term', table_name='exercise', postgresql_where='type = 4')
    op.drop_index('unique_speak_sentence', table_name='exercise', postgresql_where='type = 5')
    op.drop_index('unique_order_sentence', table_name='exercise', postgresql_where='type = 0')
    op.drop_index('unique_listen_term_mchoice', table_name='exercise', postgresql_where='type = 2')
    op.drop_index('unique_listen_term_lexical', table_name='exercise', postgresql_where='type = 1')
    op.drop_index('unique_listen_term', table_name='exercise', postgresql_where='type = 1')
    op.drop_index('unique_listen_sentence', table_name='exercise', postgresql_where='type = 3')
    op.drop_table('exercise')
    op.drop_table('term_pronunciation')
    op.drop_table('term_definition')
    op.drop_table('term_lexical')
    op.drop_table('term_image')
    op.drop_table('term_example_translation')
    op.drop_table('card')
    op.drop_table('term_example')
    op.drop_index('idx_content_language', table_name='term')
    op.drop_table('term')
    op.drop_table('cardset')
    # ### end Alembic commands ###
